kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: html-openshift-app
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
