kind: Secret 
apiVersion: v1 
metadata:
  name: html-openshift-app 
  labels:
    app: html-openshift-app 
    app.kubernetes.io/part-of: html-openshift-app 
data:
  username: flurin1234
  password: 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
type: kubernetes.io/basic-auth 
--- 
kind: Secret 
apiVersion: v1 
metadata:
  name: html-openshift-app 
  labels:
    app: html-openshift-app 
    app.kubernetes.io/part-of: html-openshift-app 
data:
  WebHookSecretKey: <key> 
type: Opaque 

